language: csharp
solution: Baseclass.SharedResource.sln
env:
- PACKAGE_VERSION=0.2.$TRAVIS_BUILD_NUMBER
install:
  - mono .paket/paket.exe restore
script:
  - xbuild /p:Configuration=Release Baseclass.SharedResource.sln
after_script:
  - nuget pack Baseclass.SharedResource/Baseclass.SharedResource.nuspec -basepath Baseclass.SharedResource -properties version=$PACKAGE_VERSION
  - if [ $TRAVIS_BRANCH = 'master' ]; then nuget push Baseclass.SharedResource.$PACKAGE_VERSION.nupkg $NUGET_API_KEY -Source https://www.nuget.org/api/v2/package ; fi
